// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyC1x35Aan33XEdrgsHvOvuGVGxGqHqfA',
    appId: '1:796795235888:web:27163ffa674197271647f5',
    messagingSenderId: '796795235888',
    projectId: 'moqat3on',
    authDomain: 'moqat3on.firebaseapp.com',
    storageBucket: 'moqat3on.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6R-vhvUwRGvR4M3KIKP5SVi61i9NUow0',
    appId: '1:796795235888:android:8cc535f5800a8f431647f5',
    messagingSenderId: '796795235888',
    projectId: 'moqat3on',
    storageBucket: 'moqat3on.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoqL2uFPIHwjRStU-2dp5AewB-UUn86Rg',
    appId: '1:796795235888:ios:5a80b7f6de9c47441647f5',
    messagingSenderId: '796795235888',
    projectId: 'moqat3on',
    storageBucket: 'moqat3on.appspot.com',
    iosClientId: '796795235888-vna0aj95e7gqt3e783hggld0jtve90dh.apps.googleusercontent.com',
    iosBundleId: 'com.example.scanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoqL2uFPIHwjRStU-2dp5AewB-UUn86Rg',
    appId: '1:796795235888:ios:28beab66198121df1647f5',
    messagingSenderId: '796795235888',
    projectId: 'moqat3on',
    storageBucket: 'moqat3on.appspot.com',
    iosClientId: '796795235888-t61162vbi6m36i1khuo341p2neqk8p8j.apps.googleusercontent.com',
    iosBundleId: 'com.example.scanner.RunnerTests',
  );
}
